
import { motion } from "framer-motion";
import { ArrowLeft, Shield, FileText, Clock } from "lucide-react";
import { useNavigate } from "react-router-dom";
import PageTransition from "@/components/motion/PageTransition";
import { FadeInUp } from "@/components/motion/MotionWrapper";

const TermsPage = () => {
  const navigate = useNavigate();

  const sections = [
    {
      title: "1. Acceptance of Terms",
      content: "By accessing and using DevSynth AI, you accept and agree to be bound by the terms and provision of this agreement."
    },
    {
      title: "2. Use License",
      content: "Permission is granted to temporarily download one copy of DevSynth AI for personal, non-commercial transitory viewing only."
    },
    {
      title: "3. User Accounts",
      content: "When you create an account with us, you must provide information that is accurate, complete, and current at all times."
    },
    {
      title: "4. AI-Generated Content",
      content: "Content generated by our AI tools is provided as-is. Users are responsible for reviewing and validating all AI-generated outputs."
    },
    {
      title: "5. Privacy Policy",
      content: "Your privacy is important to us. Please review our Privacy Policy, which also governs your use of the Service."
    },
    {
      title: "6. Limitation of Liability",
      content: "In no event shall DevSynth AI be liable for any indirect, incidental, special, consequential, or punitive damages."
    }
  ];

  return (
    <PageTransition>
      <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-white">
        {/* Navigation */}
        <nav className="p-6 border-b border-white/10 backdrop-blur-xl bg-black/20">
          <div className="container mx-auto flex items-center gap-4">
            <button
              onClick={() => navigate('/')}
              className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
              Back to Home
            </button>
          </div>
        </nav>

        <div className="container mx-auto px-6 py-16 max-w-4xl">
          {/* Header */}
          <FadeInUp>
            <div className="text-center mb-16">
              <div className="flex items-center justify-center gap-3 mb-6">
                <div className="w-16 h-16 bg-gradient-to-r from-neon-aqua to-neon-purple rounded-2xl flex items-center justify-center">
                  <FileText className="w-8 h-8 text-white" />
                </div>
                <h1 className="text-4xl font-bold font-sora bg-gradient-to-r from-neon-aqua to-neon-purple bg-clip-text text-transparent">
                  Terms of Service
                </h1>
              </div>
              <div className="flex items-center justify-center gap-6 text-gray-400">
                <div className="flex items-center gap-2">
                  <Clock className="w-4 h-4" />
                  <span>Last updated: December 15, 2024</span>
                </div>
                <div className="flex items-center gap-2">
                  <Shield className="w-4 h-4" />
                  <span>Version 1.0</span>
                </div>
              </div>
            </div>
          </FadeInUp>

          {/* Introduction */}
          <FadeInUp delay={0.2}>
            <div className="glass-dark backdrop-blur-xl rounded-3xl p-8 border border-white/10 mb-12">
              <h2 className="text-2xl font-bold mb-4 bg-gradient-to-r from-neon-coral to-neon-orange bg-clip-text text-transparent">
                Welcome to DevSynth AI
              </h2>
              <p className="text-gray-300 leading-relaxed">
                These Terms of Service ("Terms") govern your use of DevSynth AI's website and services. 
                By using our service, you agree to these terms. Please read them carefully.
              </p>
            </div>
          </FadeInUp>

          {/* Terms Sections */}
          <div className="space-y-8">
            {sections.map((section, index) => (
              <FadeInUp key={index} delay={0.3 + index * 0.1}>
                <motion.div
                  className="glass-dark backdrop-blur-xl rounded-2xl p-6 border border-white/10 hover:border-neon-aqua/30 transition-all duration-300"
                  whileHover={{ scale: 1.01 }}
                >
                  <h3 className="text-xl font-semibold text-white mb-4">{section.title}</h3>
                  <p className="text-gray-300 leading-relaxed">{section.content}</p>
                </motion.div>
              </FadeInUp>
            ))}
          </div>

          {/* Contact Information */}
          <FadeInUp delay={1.0}>
            <div className="glass-dark backdrop-blur-xl rounded-3xl p-8 border border-white/10 mt-12 text-center">
              <h2 className="text-2xl font-bold mb-4 bg-gradient-to-r from-emerald-400 to-neon-aqua bg-clip-text text-transparent">
                Questions About These Terms?
              </h2>
              <p className="text-gray-300 mb-6 leading-relaxed">
                If you have any questions about these Terms of Service, please contact us at legal@devsynth.ai
              </p>
              <button
                onClick={() => navigate('/contact')}
                className="px-8 py-3 bg-gradient-to-r from-neon-coral to-neon-aqua rounded-xl font-semibold hover:scale-105 transition-transform"
              >
                Contact Us
              </button>
            </div>
          </FadeInUp>
        </div>
      </div>
    </PageTransition>
  );
};

export default TermsPage;
