// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icrezhdcguwtqkcyhmvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcmV6aGRjZ3V3dHFrY3lobXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTAwNzMsImV4cCI6MjA2NTUyNjA3M30.6I3bez7bpHQ_j2mxN7hSWE1V3QrPVGLp9tbrV21dOR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);